language: java
script:
- mvn clean install
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: Fbw3BYLeLjkNcGT6xfcDRcUhOHmLDSHb8isD+5ug7gI0DLLnVY4hhgFs9fSPYJbkuN2b9ck8sVPw6uiNmBIrBGAjEwkuEnP3jFciq/049SkuRs5oCwIbnsJfBjTcssyAaFU26VKONfa1bUZgKbyQjMBoEk5RgXTdt7qCmT7p+ikgXcaDSNYO4d7AFQ0f1No7Wb9BCjjLR+amP1ME3spyPDCKQXB2JpdSxcdGnVGVCWDp6Cs9CEBeOOfoJWGidZMHuuBPip0MXPOd6nHwHuQi9LkABnEIKhJ8Q+trz/fLtWccSLZq39U6SwdCBBAAUJEdI09HSV4sy9EmWLodUKdG10bqQIb9AxQAX/l4d2li5ZeoijT/fT1b00grszDdLmC0RGgytgUkM8RrMH9hFChXnADpzsKr2U7kMz/7VSeDBNCfZs5wbb+cBxrgcp+yje8ULM+ssasd9HySVo1MUw7jBtZXL1Sb3Ec58SiclYo3ZcDqu4aJA4qwH4ZilXu0foZrESBv99DijRLc68IvndNuLFaahxbuLsM/FWdIFdFN20OQffLeLvT4VrjRpLean42GKx11WfkhGwm4XpOjdc2AXMDA+qlam9/CnuCj2tIpUlwxwsTSUx684ihEEoab+seiw4po/aeS0+K1RDt/qbMER0S6YQUDYhWcEjD//GB0bTw=
  file: target/workflow-cps-http.hpi
  on:
    repo: coveo/workflow-cps-http-plugin
    tags: true
