name: Build
on:
  push:
    branches:
      - master
    tags:
      - "*"
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Build
        uses: LucaFeger/action-maven-cli@1.0.2
        with:
          args: clean install -B -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn

      - name: Release Tag
        if: github.ref != 'refs/heads/master'
        uses: softprops/action-gh-release@v1
        with:
          files: target/pipeline-cps-http.hpi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
